#MyWindowManager:
#    MyGrid:
#    GameOver:

<TextLabel>:
    multiline: False
    text_size: self.size
    font_size: min( self.height*0.8, self.width/(1+0.6*len(self.text)) )
    valign: "middle"
        
<MultilineTextLabel>:
    multiline: True
    text_size: self.size
    font_size: ( self.height*self.width / (1+ len(self.text)) )**0.5
    valign: "top"

<Button>:
    text_size: self.size
    font_size: min( self.height*0.6, self.width/(1+0.6*len(self.text)) )
    halign: "center"
    valign: "middle"

<MyGrid>:
    name: "game_screen"
        
    target: target
    factors: factors
    running_input: running_input
    time_display: time_display
    b1:b1
    b2:b2
    b3:b3
    b4:b4
    b5:b5
    b6:b6
    b7:b7
    b8:b8
    b9:b9
    b0:b0
        
    GridLayout:
        size: root.width, root.height
        cols:1
            
        TextLabel:
            text: "Target:"
            size_hint_y: 0.2
        
        TextLabel:
            id: target
            text: self.text
            size_hint_y: 1
            valign: "top"
                
        TextLabel:
            text: "Prime Factors:"
            size_hint_y: 0.2

        TextLabel:
            id: factors
            text: self.text
            size_hint_y: 0.5
            valign: "top"
                    
        MultilineTextLabel:
            text: "instructions:\nPress the prime factors of the target number, in order from smallest to largest.\ne.g. if your target is 66, the prime factors are 2, 3, and 11 (since these are the prime numbers which multiply to make 66). so you would press 2 3 1 1."
            valign: "middle"
            size_hint_y: 1
        
        ProgressBar:
            id: time_display
            min: 0
            max: 1
            size_hint_y: 0.05
        
        GridLayout:
            cols:2
                
            TextLabel:
                id: running_input
                text: self.text
            
            GridLayout:
                cols:1
                
                GridLayout:
                    cols:3

                    size_hint_y: 2.2

                    Button:
                        id:b1
                        text: "1"
                        on_press:
                            root.submit(self.text)
                    Button:
                        id:b2
                        text: "2"
                        on_press:
                            root.submit(self.text)
                    Button:
                        id:b3
                        text: "3"
                        on_press:
                            root.submit(self.text)
                    Button:
                        id:b4
                        text: "4"
                        on_press:
                            root.submit(self.text)
                    Button:
                        id:b5
                        text: "5"
                        on_press:
                            root.submit(self.text)
                    Button:
                        id:b6
                        text: "6"
                        on_press:
                            root.submit(self.text)
                    Button:
                        id:b7
                        text: "7"
                        on_press:
                            root.submit(self.text)
                    Button:
                        id:b8
                        text: "8"
                        on_press:
                            root.submit(self.text)
                    Button:
                        id:b9
                        text: "9"
                        on_press:
                            root.submit(self.text)
                Button:
                    id:b0
                    text: "0"
                    on_press:
                        root.submit(self.text)

                
<GameOver>:
    name: "game_over_screen"
        
    info_to_display: info_to_display
        
    GridLayout:
        size: root.width, root.height
        cols: 1
        
        TextLabel:
            text: "Game Finished"
            halign: "center"
            size_hint_y: 0.2
                
        Label:
            id: info_to_display
            text: self.text
            text_size: self.size
            font_size: self.height / 10
            halign: "left"
            size_hint_y: 1

        Button:
            text: "Try Again"
            on_press: root.restart()