#: kivy 2.0.0

<TextLabel>:
    multiline: False
    text_size: self.size
    font_size: min( self.height*0.8, self.width/(0.1+0.6*len(self.text)) )
    valign: "middle"
        
<MultilineTextLabel>:
    multiline: True
    text_size: self.size
    font_size: ( self.height*self.width / (1+ len(self.text)) )**0.5
    valign: "top"

<Button>:
    text_size: self.size
    font_size: min( self.height*0.6, self.width/(1+0.6*len(self.text)) )
    halign: "center"
    valign: "middle"

<MyGrid>:
    name: "game_screen"
        
    GridLayout:
        size: root.width, root.height
        cols:1
            
        TextLabel:
            text: "Target:"
            size_hint_y: 0.3
        
        TextLabel:
            id: target
            text: self.text
            size_hint_y: 1.75
            valign: "top"
                
        TextLabel:
            text: "Prime Factors:"
            size_hint_y: 0.3
        
        GridLayout:
            cols:2
            size_hint_y: 0.5
                
            TextLabel:
                id: factors
                text: self.text
                size_hint_x: 5
                valign: "top"
                    
            TextLabel:
                id: running_input
                text: self.text
                halign: "center"
        
        Graph:
            id: TTS_graph
            xlabel: "level"
            ylabel: "time"
            size_hint_y: 1
        
        GridLayout:
            cols:4
            size_hint_y: 0.5
                
            Button:
                id: instructions_btn
                text: "i"
                background_normal: ''
                background_color: (0.36,0.67,0.87)
                on_press: root.show_info()
                size_hint_x: 0.25
                    
            Button:
                id: stats_btn
                text: 'stats'
                on_press: root.show_stats()
                    
            TextLabel:
                text: 'mode:'
                halign: "right"
            
            Button:
                id: mode_btn
                on_press: root.cycle_mode()
        
        ProgressBar:
            id: time_display
            min: 0
            max: 1
            size_hint_y: 0.05

        GridLayout:
            cols:2
            size_hint_y: 1.5
            
            Button:
                size_hint_x: 0.2
                text: "0"
                on_press:
                    root.submit(self.text)

            GridLayout:
                cols:3

                #size_hint_y: 2.2

                Button:
                    text: "1"
                    on_press:
                        root.submit(self.text)
                Button:
                    text: "2"
                    on_press:
                        root.submit(self.text)
                Button:
                    text: "3"
                    on_press:
                        root.submit(self.text)
                Button:
                    text: "4"
                    on_press:
                        root.submit(self.text)
                Button:
                    text: "5"
                    on_press:
                        root.submit(self.text)
                Button:
                    text: "6"
                    on_press:
                        root.submit(self.text)
                Button:
                    text: "7"
                    on_press:
                        root.submit(self.text)
                Button:
                    text: "8"
                    on_press:
                        root.submit(self.text)
                Button:
                    text: "9"
                    on_press:
                        root.submit(self.text)
                

                
<GameOver>:
    name: "game_over_screen"
        
    info_to_display: info_to_display
        
    GridLayout:
        size: root.width, root.height
        cols: 1
        
        TextLabel:
            text: "Game Finished"
            halign: "center"
            size_hint_y: 0.2
                
        Label:
            id: info_to_display
            text: self.text
            text_size: self.size
            font_size: self.height / 10
            halign: "left"
            size_hint_y: 1
        
        Graph:
            id: ST_graph
            xlabel: "game time"
            ylabel: "score"
            size_hint_y: 1
        
        Button:
            text: "Try Again"
            on_press: root.restart()
                
                
                
                
                
<info>:
    name: "info_screen"
    
    GridLayout:
        size: root.width, root.height
        cols: 1
            
        MultilineTextLabel:
            text: "instructions:\nPress the prime factors of the target number, in order from smallest to largest.\ne.g. if your target is 66, the prime factors are 2, 3, and 11 (since these are the prime numbers which multiply to make 66). so you would press 2 3 1 1.\nThe size of the target numbers increases as time progresses from the game start, so answering quickly will help you keep the targets manageable for longer.\nHit the mode button to toggle between normal and training modes. Training mode gives you targets that you are likely not confident with, based on your history. No data is saved from your games in training mode."
            #valign: "middle"
            font_size: 1.15*( self.height*self.width / (1+ len(self.text)) )**0.5
            size_hint_y: 3

        Button:
            text: "Play"
            on_press: root.restart()
                
                
                
                
                
<stats>:
    name: "stats_screen"
    
    GridLayout:
        size: root.width, root.height
        cols: 1
                
        Graph:
            id: WRN_graph
            xlabel: "target"
            ylabel: "chance of success"
            size_hint_y: 1

        Graph:
            id: TN_graph
            xlabel: "target"
            ylabel: "avg time"
            size_hint_y: 1

        Button:
            text: "Play"
            on_press: root.restart()